baseURL = 'https://ninunez14.github.io/'
languageCode = 'es-us'
title = 'Nicolás Núñez'
theme = 'PaperMod'

[params]
    defaultTheme = 'dark' 
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    description = "Hola mundo"

[menu]
  [[menu.main]]
    identifier = "proyectos"
    name = "Proyectos"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/ninunez14"
    weight = 20
